# Generated by Django 5.0.4 on 2024-04-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('request_type', models.CharField(choices=[('repair', 'Repair'), ('installation', 'Installation'), ('maintenance', 'Maintenance')], max_length=20)),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='service_requests/')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
